### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by GARLICDOG** [RundownRhino/aw-watcher-mpv-sender#9]
I'm not sure if this is intended or if it's an issue on my end but the mpv watcher has a high CPU load even when the mpv player is not running.

Specifically I have an AMD Ryzen 5 3600 (6 cores running on 3800 mhz) on Windows 11
mpv_websocket.exe is using a stable 18%+ of the CPU making it the highest load by far
aw-watcher-mpv.exe is also hovering around 8-10%

This is without running or using the player. If I watch something these might bump by 1-2%.

Is it possible to somehow idle the watcher or only start these exes when the player is running? I have enough overhead to spare but since I started using the mpv-watcher I've already encountered a few situations where there was noticeable jitter due to the CPU getting maxed out.

**Comment by RundownRhino** [comment]
There was a bug in v0.2.2 causing this. What version are you using?

**Comment by GARLICDOG** [comment]
I just checked it v0.2.2 forgot to mention I remembered it was a new release so thought it wasn't a version issue. Updated and the the issue is resolved completely. Thanks for the quick update & help!
